name: Backend, Frontend, and Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  backend-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies for backend
        run: |
          cd express-mock-interview
          npm install

      - name: Start backend server
        run: |
          cd express-mock-interview
          npx nodemon index.js &
        env:
          PORT: 3000

      - name: Install dependencies for frontend
        run: |
          cd fe-test-task
          npm install
          npm start &
      
      - name: Install dependencies for Cypress tests
        run: |
          cd testing
          npm install
          npx cypress install

      - name: Run Cypress tests
        run: |
          cd testing
          npx cypress run
