name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variable
        run: echo "CYPRESS_deviceName=desktop" >> $GITHUB_ENV

      - name: Install and start backend
        run: |
          cd express-mock-interview/
          npm install
          npm start
        env:
          NODE_ENV: production

      - name: Install and start frontend
        run: |
          cd fe-test-task/
          npm install
          npm run dev
        env:
          NODE_ENV: production

      - name: Wait for servers to start
        run: sleep 10

      - name: Run Cypress tests
        run: |
          cd testing/
          npx cypress run
