name: Backend and Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  backend-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for backend
        run: |
          cd express-mock-interview
          npm install
          npm install nodemon --save-dev

      - name: Start backend server
        run: |
          cd express-mock-interview
          npx nodemon index.js &

      - name: Install dependencies for frontend
        run: |
          cd fe-test-task
          npm install
          npm start &

      - name: Run Cypress tests
        run: |
          cd testing
          npm install
          npx cypress run

